### ISSUE TITLE
Uploading A Chapter Does Not Redirect

### ISSUE THREAD

**Issue by lehitoskin** [RamuneDeveloper/Ramune#2]
Problem:
After uploading a chapter to a series, the page is stuck at the "Success!" message and does not redirect back to the main page or the Upload page. Reloading from the the success message gives the error "Cannot GET /api/upload".

Expected behavior:
After uploading a chapter, the page will redirect to the Upload screen

Actual behavior:
Page stays at the "Success!" message.

Steps to reproduce:
1. Fill out information to upload new manga chapter
2. Click Browse button to select ZIP with chapter's contents
3. Click Submit button

**Comment by RamuneDeveloper** [comment]
Fixed, you are now redirected to the manga you uploaded to when submitting a new release.
